version: "3.8"
services:
  digit-counter-api:
    build:
      context: .
      args:
        FAKE_SECRET: password123
    environment:
      ENV: production
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
