name: Test Digit Counter

on:
  - push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        env:
          FAKE_SECRET: ${{ secrets.FAKE_SECRET }}
          DOCKER_BUILDKIT: "1"
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml build

      - name: Test
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml up --abort-on-container-exit

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-artifacts/test-results.xml
