name: Test Digit Counter

on:
  - push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run Tests

    services:

      redis:
        image: redis:6.2-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 2s
          --health-timeout 5s
          --health-retries 25

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build
        env:
          FAKE_SECRET: ${{ secrets.FAKE_SECRET }}
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: a-forsythe/digit-counter:latest
          load: true
          secrets: |
            "fake=${{ secrets.FAKE_SECRET }}"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Swap Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Test
        run: >-
          docker run
            -e ENV=test
            -e TEST_ARTIFACTS_PATH=/test-artifacts
            -e REDIS_URL=redis://redis:6379/0
            -v "$(pwd)/test-artifacts:/test-artifacts"
            a-forsythe/digit-counter

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-artifacts/test-results.xml
