name: Test Digit Counter

on:
  - push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml build

      - name: Test
        env:
          DOCKER_BUILDKIT: "1"
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml up --abort-on-container-exit
