name: Test Digit Counter

on:
  - push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t digit-counter

      - name: Test
        run: docker run -e ENV=test digit-counter
