name: Test Digit Counter

on:
  - push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Build
        env:
          FAKE_SECRET: ${{ secrets.FAKE_SECRET }}
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml build

      - name: Test
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml up --abort-on-container-exit

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-artifacts/test-results.xml
