name: Test Digit Counter

on:
  - push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml up --build --abort-on-container-exit
