name: Test Digit Counter

on:
  - push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run Tests

    services:

      redis:
        image: redis:6.2-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 2s
          --health-timeout 5s
          --health-retries 25
        ports:
          - "6379:6379"

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        env:
          IMAGE_TAG: sha-${{ github.sha }}
        run: |
          export DOCKER_BUILDKIT=1
          echo "version='$IMAGE_TAG'" > src/__version__.py
          docker build \
            --build-arg FAKE_SECRET=${{ secrets.FAKE_SECRET }} \
            --tag test/digit-counter:$IMAGE_TAG \
            .

      - name: Test
        run: |
          docker run \
            -e ENV=test \
            -e TEST_ARTIFACTS_PATH=/test-artifacts \
            -e REDIS_URL=redis://$(docker network inspect bridge --format='{{(index .IPAM.Config 0).Gateway}}'):6379/0 \
            -v "$(pwd)/test-artifacts:/test-artifacts" \
            test/digit-counter:sha-${{ github.sha }}

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-artifacts/test-results.xml
