name: Test Digit Counter

on:
  - push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        env:
          FAKE_SECRET: ${{ secrets.FAKE_SECRET }}
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: a-forsythe/digit-counter:latest
          secrets: |
            "fake=${{ secrets.FAKE_SECRET }}"

      - name: Test
        run: |
          docker run \
            -e ENV=test \
            -e TEST_ARTIFACTS_PATH=/test-artifacts \
            -v "$(pwd)/test-artifacts:/test-artifacts" \
            a-forsythe/digit-counter

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-artifacts/test-results.xml
