name: Test Digit Counter

on:
  - push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install prerequisites
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./src

      - name: Test
        run: pytest tests
        working-directory: ./src
